- README.md
Not sure if we want to put anything else here, seems a bit empty.
> Link out to enterprise CLI docs

- cmd/coder/shell.go
- go.mod
- go.sum
> Fix coder sh freeze

- cmd/coder/shell.go
This may be unnecessary if heatbeat is an inside joke. :)
> Rename heatbeat to heartbeat.

- .github/workflows/build.yaml
> Add github action to build releases

- cmd/coder/shell.go
This is a hotfix for a common shell disconnect case. Future enhancements will poll for the environment status and display a more actionable message.
Progress towards #87 
```
$ coder sh development
2020-08-03 09:55:21 FATAL	run command: network error, is "development" online?
```
> Show network error on unexpected disconnect

- coder-sdk/env.go
- coder-sdk/image.go
- coder-sdk/ws.go
These new public functions will be used for our new load testing harness for the enterprise product
> Add ability to create new environments and images to the coder-sdk

- ci/steps/build.sh
> Distribute windows artifact as coder.exe in a .zip

- coder-sdk/env.go
- internal/x/xtabwriter/tabwriter.go
Closes #106 
```
$ coder envs ls                                                                         
Name                ImageTag    CPUCores    MemoryGB    DiskGB    GPUs    Updating    Status    
dev                 latest      4           4           40        0       false       ON        
test-datascience    latest      4           4           10        0       false       OFF       
entdev              latest      2           4           11        0       false       OFF       
test-goland         latest      2           2           30        0       false       OFF 
```
> Add environment status to "envs ls"

- internal/cmd/configssh.go
> Remove dependency on HOME env var

- ci/integration/setup_test.go
- cmd/coder/main.go
- coder-sdk/activity.go
- coder-sdk/client.go
- coder-sdk/devurl.go
- coder-sdk/env.go
- coder-sdk/error.go
- coder-sdk/image.go
- coder-sdk/org.go
- coder-sdk/request.go
- coder-sdk/secrets.go
- coder-sdk/users.go
- coder-sdk/ws.go
- internal/activity/pusher.go
- internal/activity/writer.go
- internal/cmd/auth.go
- internal/cmd/ceapi.go
- internal/cmd/cmd.go
- internal/cmd/configssh.go
- internal/cmd/secrets.go
- internal/cmd/shell.go
- internal/cmd/urls.go
- internal/cmd/users.go
- internal/sync/sync.go
- internal/x/xjson/duration.go
- internal/x/xtabwriter/tabwriter.go
- internal/x/xterminal/terminal.go
- internal/x/xterminal/terminal_windows.go
- Scope errors when possible.
- Fix nil pointers in unmarshal.
- Align struct tags for readability.
- Explicitly discard errors with a comment on why.
- Import package order.
- Fmt verb for types.
- More comments.
> Minor clean / tidying up the code

- internal/cmd/auth.go
- internal/cmd/configssh.go
- internal/cmd/envs.go
- internal/cmd/secrets.go
- internal/cmd/shell.go
- internal/cmd/sync.go
- internal/cmd/urls.go
- internal/cmd/users.go
> Remove fatal calls from sdk client creation

- coder-sdk/error.go
- internal/cmd/auth.go
- internal/cmd/shell.go
> Give better error when authentication expires [ch134]

- internal/cmd/configssh.go
Fixed the errors coming from the ssh key write process to better reflect when the ssh key already exists or not.
> fixed ssh key error to better reflect its state.

- internal/cmd/rebuild.go
The typical loaders only work properly when the output is a terminal. This PR detects whether stdout is a terminal and toggles plain/dynamic output accordingly.
> Fix rebuild output for non-terminals

- ci/steps/build.sh
> Compile without cgo for Linux

- coder-sdk/env.go
- docs/coder_sh.md
- internal/cmd/cmd.go
- internal/cmd/configssh.go
- internal/cmd/envs.go
- internal/cmd/login.go
- internal/cmd/logout.go
- internal/cmd/secrets.go
- internal/cmd/shell.go
- internal/cmd/sync.go
- internal/cmd/urls.go
- internal/cmd/users.go
https://app.clubhouse.io/coder/story/352/reject-or-warn-on-coder-sh-when-an-environment-needs-to-be-rebuilt
> Error coder sh commands if the env requires a rebuild

- .github/workflows/build.yaml
- ci/gon.json
- ci/steps/build.sh
> Add notarization of MacOS binary to CI

- coder-sdk/image.go
This should cause Coder to refresh the latest digests for the image tags.
> Add method to refresh image tags SHAs

- coder-sdk/client.go
- coder-sdk/env.go
- docs/coder_envs_create.md
- docs/coder_envs_edit.md
- internal/cmd/envs.go
> Add cvm flag to CLI and fields to coder-sdk

- coder-sdk/image.go
Pulling this into master from the preview release branch: https://github.com/cdr/coder-cli/compare/release-v1.13.x
> feat: add tag refresh method to coder-sdk

- coder-sdk/env.go
- coder-sdk/resourcepools.go
> feat: add coder-sdk methods for multi-cluster

- coder-sdk/env.go
- coder-sdk/org.go
- coder-sdk/request.go
- coder-sdk/users.go
- coder-sdk/ws.go
- internal/cmd/ceapi.go
- internal/cmd/envs.go
- The structure of our routing tree is being refactored
as part of the effort to prepare our API for public consumption.
This PR fixes some routes that were broken in a way that was not
backwards compatible.
> chore: update API-breaking environment routes

- coder-sdk/env.go
- internal/cmd/envs.go
> feat: add envs create-from-repo subcommand

- coder-sdk/client_test.go
- coder-sdk/request.go
- go.sum
Append, rather than overwrite, request paths, so that we can invoke
requests on custom context roots.
> feat: configurable context root support

- coder-sdk/env.go
- docs/coder_envs_create.md
- internal/cmd/envs.go
- internal/cmd/rebuild.go
This reverts commit dd7b3a982bd4cf05e8f63ab85e999fbe0261e280.
This commit should be re-reverted once the feature is
readied from the internal stage.
> Revert "feat(cli): AutoStart education notice [ch7441] (#236)"

- internal/cmd/ceapi.go
- internal/cmd/envs.go
Orgid is a required field for wac as we moved it out of the template
> Add orgid to wac envs create

- docs/coder_envs_edit.md
- internal/cmd/envs.go
- internal/cmd/envs_test.go
- internal/cmd/rebuild.go
See CH9720 https://app.clubhouse.io/coder/story/9720/confirm-when-editing-environment-with-coder-cli
> Add confirmation prompt to 'coder envs edit'

- .gitignore
Lil artifact from another PR. Added to .gitignore so it can't happen again.
> fix: Remove built bin at root

- agent/stream.go
- internal/cmd/tunnel.go
- internal/x/xwebrtc/conn.go
- pkg/proto/message.go
This feature is under a feature flag in the product at a deployment level, so there's no risk of security gaps here.
> feat: Use internal TURN server for proxying

- internal/cmd/tunnel.go
- wsnet/auth.go
Uses the token for authentication. PR comin' up in `m`.
> feat: Add authentication to TURN

- wsnet/listen.go
> fix: Stop infinite read loop on control channel

- internal/cmd/configssh.go
- internal/cmd/tunnel.go
Uses the proxy server instead of 22.
> fix: Change SSH port for p2p

- wsnet/dial_test.go
https://github.com/cdr/coder-cli/runs/2560162377
> fix: TestDial/EOF_on_Close listen race

- coder-sdk/activity.go
- coder-sdk/error.go
- coder-sdk/request.go
- coder-sdk/ws.go
- internal/cmd/auth.go
- internal/cmd/errors.go
- wsnet/dial.go
- wsnet/listen.go
Resolves:
https://app.clubhouse.io/coder/story/12938/remove-http-response-from-httperror-in-coder-sdk
> Adjust HTTPError to read response body before it is closed

- internal/cmd/configssh.go
- wsnet/listen.go
Speedy speedy speed...
Works for Linux and Darwin systems, [but not Windows](https://github.com/microsoft/vscode-remote-release/issues/629#issuecomment-503650294).
https://user-images.githubusercontent.com/7122116/124811861-8e0f8600-df28-11eb-8925-51a301e5ff54.mp4
> chore: Cache SSH connections

- go.mod
- internal/cmd/agent.go
- wsnet/dial_test.go
- wsnet/listen.go
- wsnet/listen_test.go
> Add logs to wsnet listener

- wsnet/cache.go
- wsnet/conn.go
- wsnet/dial.go
- wsnet/dial_test.go
The `Closed` function was causing more problems then it fixed...
> chore: Remove Closed chan in favor of reconnecting DataChannels

- wsnet/dial.go
- wsnet/error.go
Doesn't contain all of the details in the ticket, but you've gotta start somewhere.
[CH-15066]
> Add err wrapping to dialer

- go.mod
- go.sum
- internal/cmd/tunnel.go
- pkg/clog/clog.go
Very fun lil hack to display user output on an SSH connection to offline workspaces.
Here's what it looks like from VS Code:
> feat: Display error to user when SSHing into offline workspace

- pkg/clog/clog.go
- pkg/clog/clog_test.go
- pkg/clog/errgroup_test.go
Occasionally SSH connections wouldn't return on newlines... this fixes it!
Before:
After:
> chore: Add line returns to clog output

- README.md
> chore: add note this is the CLI for Coder Classic

- internal/cmd/login.go
- internal/coderutil/workspace.go
- wsnet/listen.go
> feat: add username to 'coder ws ls'

- .github/workflows/release.yaml
- README.md
Adding to the "releases" page too
> chore: add more v1 warnings
