coder/coder-v1-cli

cmd/coder/shell.go, wush/client.go
Closes #28 
Prints the error returned from wush-lite instead of identifying it as an invalid stream id
Before:
After:
=> Properly handle wush error messages

cmd/coder/configssh.go
Also: use idiomatic file name.
=> Tolerate absent ~/.ssh/config

cmd/coder/shell.go, go.mod, go.sum
This upgrades `wsep` to the latest version that includes a patch to exit-codes caused by a race condition. This will also fix the issue @wbobeirne had when pulling with `go get -u cdr.dev/coder-cli`.
=> Fix exit code

cmd/coder/sync.go, internal/sync/sync.go
I just noticed that setting up sync on a new Environment requires going in first with `coder sh` to create intermediate subdirs of the desired remote path. This patch makes that unnecessary, automatically creating the remote path if not already existent.
=> Sync fails if path leading to remoteDir doesn't already exist

cmd/coder/login.go
Fixes #53 
Detects a user entering a URL without the protocol field, eg. 'localhost:8080' instead of 'http://localhost:8080' which would result in a malformed login URL, and the stored state using incorrect API paths for all coder-cli operations (eg. sync, sh) which give obscure rsync errors.
Since the cli library dispatches sub-commands to the login.Run() function as non-writable array fl.Arg(), the URL can't be patched up silently to be correct, so instead this patch detects the missing protocol prefix in the URL, and prints out a help usage modified to explain that http[s]:// is required.
=> login: detect missing protocol in URL

cmd/coder/sync.go
* Improve checking for rsync errors in initial sync
* Suggest to user what might be wrong (in this case, missing rsync in remote environment)
While trying out coder-cli on my own dev server, I had used a base ubuntu docker image for my environment. It doesn't install rsync by default, so `coder sync` fails with obscure "rsync: exit status 12".
It took a while for me to realize `rsync` wasn't installed in the environment. We should make coder-cli suggest actions to resolve the issue to the user.
Also, I suspect the existing check for incompatible rsync protocol won't work, as the errors returned from the sync internal package are xerrors vs. the plain error type declared to compare errors against. When I tried adding the equivalent check for error status 12, following the example for exit …
=> Rsync error msgs

cmd/coder/sync.go, cmd/coder/urls.go, internal/entclient/activity.go, internal/entclient/devurl.go, internal/sync/sync.go
This implements the new subcommands proposed in #57 
```
$ ./coder urls russ-env1
http://3000-russ-env1-admin.russtopia-rlmfuntoo.dogfood.c8s.io/ 3000 PRIVATE
```
```
$ ./coder urls create russ-env1 3001 --access=org
Adding devurl for port 3001
$ ./coder urls russ-env1
http://3000-russ-env1-admin.russtopia-rlmfuntoo.dogfood.c8s.io/ 3000 PRIVATE
http://3001-russ-env1-admin.russtopia-rlmfuntoo.dogfood.c8s.io/ 3001 ORG
```
```
$ ./coder urls create russ-env1 3002 -a group
Invalid access level
Usage: coder urls create <env name> <port> [--access <level>]
create/update a devurl for external access
coder urls create flags:
-a, --access string   [private | org | authed | public] set devurl access (default "private")
```
```
$ ./coder urls del russ-env1 8000
2020-06-25 09:38:25 FATAL	No devurl …
```
=> Devurl crud ops

cmd/coder/sync.go, internal/sync/sync.go
`sync.Version()` proceeds with a warning that there may be a version
mismatch if it timesout.
`syncCmd.version` assumes rsync is present in the path.
`wsep` integration is currently unverified.  Verification is next.
Potentially closes #65.
=> Verify rsync protocol version match prior to proceeding - Rebased on current master.

ci/integration/integration_test.go, cmd/coder/envs.go, cmd/coder/logout.go, cmd/coder/main.go, cmd/coder/shell.go, cmd/coder/users.go, cmd/coder/version.go, internal/entclient/me.go, internal/entclient/users.go
Related to #76 
```
$ coder users ls -o json | jq -c '.[] | select( .username == "charlie")' 
{"id":"5e8decf9-563f9fb3a7c02f6e0eafa422","email":"charlie@coder.com","username":"charlie","name":"Charlie","created_at":"2020-04-08T15:25:45.419609Z"}
$ coder users ls -o human | grep charlie
5e8decf9-563f9fb3a7c02f6e0eafa422        charlie@coder.com           charlie                                         Charlie   2020-04-08 15:25:45.419609 +0000 UTC
```
=> Add list users command

ci/tcli/tcli.go
This allows the integrations tests to point towards a mocked `cemanager` instances on Coder branch tests.
=> Run tcli container on host network

cmd/coder/auth.go, cmd/coder/ceapi.go, cmd/coder/configssh.go, cmd/coder/envs.go, cmd/coder/main.go, cmd/coder/secrets.go, cmd/coder/shell.go, cmd/coder/sync.go, cmd/coder/urls.go, cmd/coder/users.go, internal/activity/pusher.go, internal/activity/writer.go, internal/entclient/activity.go, internal/entclient/client.go, internal/entclient/devurl.go, internal/entclient/env.go, internal/entclient/me.go, internal/entclient/org.go, internal/entclient/request.go, internal/entclient/secrets.go, internal/entclient/users.go, internal/sync/sync.go
Setting a secret value for all users. Of course, were the admin to want a different value for each user, they would need to have some additional way of correlating the email to a secret prior to creating the Coder secret.
```bash
#!/bin/bash
emails=$(coder users ls --output json | jq -c -r '.[] | .email')
for user in $emails
do
coder secrets --user $user create mysql-password --from-literal password123 
done
```
Closes #76
=> Add --user flag to "secrets" and "envs"

coder-sdk/env.go
This blocks https://github.com/cdr/c/pull/5206
- Fixes a bug where create environments returned nil always (oops)
- Adds new dial endpoints that are used for stress testing
- Adds WaitForEnvironmentReady utility on the sdk client
=> Add ws dials for resource load and ide status

ci/steps/build.sh
We weren't building the windows version on anything except darwin. Darwin will now build all versions, but linux will only build windows and linux versions.
=> Build for windows when building on linux

coder-sdk/error.go
The Go `json` struct tag knows nothing of the option `required`.
https://golang.org/pkg/encoding/json/
=> coder-sdk: remove spurious JSON tag

.github/workflows/test.yaml, docs/coder_login.md, go.mod, internal/cmd/login.go, internal/config/file.go, internal/loginsrv/input.go, internal/loginsrv/input_test.go, internal/loginsrv/server.go, internal/loginsrv/server_test.go
Loosely based on how concourse ci handles it.
Fixes #107. This makes for a better experience when using the cli over ssh.
Notable change: use the full URL given by the user instead of trimming down the path. This allows for path based reverse proxies.
=> Manual token input during login.

internal/cmd/configssh.go
I have added quotes for the identity file to enable it to work with paths that have white spaces (in a windows username for example).
=> added quotes for identity to

internal/cmd/configssh.go
Exit with an error if the failure to write the SSH private key file is anything except for an `os.ErrPermission`
=> Check for perm error in coder config-ssh

internal/cmd/cmd.go, internal/cmd/resourcemanager.go
This PR implements the following flags for `coder resources top`
```
--org string       filter by the name of an organization
--show-empty       show groups with zero active environments
--sort-by string   field to sort aggregate groups and environments by (cpu|memory) (default "cpu")
--user string      filter by a user email
```
=> Add resource top flags for filtering and sorting

coder-sdk/env.go, go.mod, go.sum, internal/cmd/envs.go, internal/cmd/rebuild.go
```
$ coder envs rebuild entdev --follow
Rebuild environment "entdev"? (will destroy any work outside of /home): y█
✅ -- 2020-10-20T00:43:06Z Ensuring private SSH key
✅ -- 2020-10-20T00:43:06Z Deleting old environment
✅ -- 2020-10-20T00:43:50Z Deleting old network isolation policy
✅ -- 2020-10-20T00:43:50Z Deleting old service
✅ -- 2020-10-20T00:43:51Z Getting default user from image
✅ -- 2020-10-20T00:43:56Z Ensuring environment has a home volume
✅ -- 2020-10-20T00:43:56Z Creating network isolation policy
✅ -- 2020-10-20T00:43:56Z Ensuring environment service
```
=> Add coder envs rebuild and watch-build commands

cmd/coder/main.go, coder-sdk/error.go, go.mod, internal/activity/pusher.go, internal/clog/error.go, internal/cmd/auth.go, internal/cmd/ceapi.go, internal/cmd/envs.go, internal/cmd/login.go, internal/cmd/logout.go, internal/cmd/rebuild.go, internal/cmd/resourcemanager.go, internal/cmd/secrets.go, internal/cmd/shell.go, internal/cmd/sync.go, internal/cmd/urls.go, internal/sync/eventcache.go, internal/sync/sync.go
Inspired by the `cargo` message formatting.
=> Add new rich error messages

ci/integration/envs_test.go, ci/steps/gendocs.sh, coder-sdk/env.go, docs/coder.md, docs/coder_completion.md, docs/coder_config-ssh.md, docs/coder_envs.md, docs/coder_envs_ls.md, docs/coder_envs_stop.md, docs/coder_login.md, docs/coder_logout.md, docs/coder_secrets.md, docs/coder_secrets_create.md, docs/coder_secrets_ls.md, docs/coder_secrets_rm.md, docs/coder_secrets_view.md, docs/coder_sh.md, docs/coder_sync.md, docs/coder_urls.md, docs/coder_urls_create.md, docs/coder_urls_ls.md, docs/coder_urls_rm.md, docs/coder_users.md, docs/coder_users_ls.md, internal/cmd/cmd.go, internal/cmd/envs.go
Adds the `create` command to the `envs` command.
```
Create a new environment under the active user.
Usage:
coder envs create [environment_name] [flags]
Examples:
coder envs create --image id-of-imported-image my-env-name
coder envs create --cores 4 --disk 100 --memory 8 --image id-of-imported-image --org id-of-existing-organization my-env-name
coder envs create -c 4 -d 100 -m 8 -i id-of-imported-image -o id-of-existing-organization my-env-name
Flags:
-c, --cpu float32      number of cpu cores the environment should be provisioned with. (default 1)
-d, --disk int         GB of disk storage an environment should be provisioned with. (default 10)
--follow           follow buildlog after initiating rebuild
-g, --gpus int         number GPUs an environment should be provisioned with.
-h, …
```
=> Add envs create command

go.mod, go.sum, internal/cmd/envs.go
Adds the `edit` command to the `envs` command.
```         
Edit an existing environment owned by the active user.
Usage:
coder envs edit [flags]
Examples:
coder envs edit back-end-env --cores 4
coder envs edit back-end-env --disk 20
Flags:
-c, --cpu float32      The number of cpu cores the environment should be provisioned with.
-d, --disk int         The amount of disk storage an environment should be provisioned with.
--follow           follow buildlog after initiating rebuild
-g, --gpu int          The amount of disk storage to provision the environment with.
-h, --help             help for edit
-i, --image string     image ID of the image you wan't the environment to be based off of.
-m, --memory float32   The amount of RAM an environment should be provisioned with.
-t, --tag string …
```
=> Add coder envs edit command

internal/cmd/envs.go
Adds a new command
```
coder envs rm [...environment_names] [flags]
```
=> Add coder envs rm command for removing environments

ci/integration/envs_test.go, coder-sdk/image.go, internal/clog/error.go, internal/cmd/ceapi.go, internal/cmd/envs.go
- Users can pass the image name to the `--image` flag instead of having to pass the image id.
- This applies to both coder `create` and `edit`
- Coder `create` and `edit` both now source default resource amounts based on the imported image vs arbitrary ones we had previously defined in the CLI.
This screenshot also demonstrates some examples of errors users might have.
When an environment image is changed and resource amounts are left unspecified, the resource amounts will be changed to that of the default resource amounts specified by the new image the environment will be using.
Also not there's a caveat here in the screenshot it's worth being aware of. Notice when we are going from `codercom/enterprise-dev` to `ubuntu` that we get a warning message about how we can't reduce the amount …
=> Change coder create | edit envs image flag to take image name and source defaults from image

docs/coder_envs.md, docs/coder_envs_rebuild.md, docs/coder_envs_watch-build.md, internal/cmd/envs.go, internal/cmd/rebuild.go
This PR unhides and generates documentation for two new subcommands:
```
$ coder envs rebuild [env_name]
$ coder envs watch-build [env_name]
```
=> Unhide rebuild and watch-build commands

docs/coder_envs.md, docs/coder_envs_rm.md, internal/clog/error.go, internal/cmd/auth.go, internal/cmd/envs.go
This PR unhides and generates documentation for the `coder envs rm` command.
=> Unhide coder envs rm command

.github/workflows/integration.yaml, ci/integration/Dockerfile, ci/integration/devurls_test.go, ci/integration/envs_test.go, ci/integration/integration_test.go, ci/integration/setup_test.go, ci/integration/users_test.go, ci/steps/integration.sh, go.mod
This PR adds integration tests for `coder envs create` and `coder envs edit`. Given that we do not have an interface for importing images, it's best that we hold off on making these test fully stateless.
=> Add basic env create|edit integration tests

.gitignore, .golangci.yml, ci/integration/devurls_test.go, ci/integration/envs_test.go, ci/integration/integration_test.go, ci/steps/unit_test.sh, coder-sdk/config.go, coder-sdk/config_test.go, coder-sdk/doc.go, coder-sdk/secrets.go, coder-sdk/users.go, coder-sdk/version.go, internal/cmd/auth.go, internal/cmd/configssh.go, internal/cmd/envs.go, internal/cmd/shell.go, internal/cmd/urls.go, internal/cmd/users.go, internal/sync/eventcache.go, internal/x/xterminal/terminal.go
I'm thinking we have the unit tests in cdr/c run the `coder-sdk` unit tests pointed at the test API server and database. We're not really able to run the tests here until we have proper test clusters.
=> Add config sdk methods

.github/workflows/release.yaml, ci/steps/build.sh
This PR adds a new Github Action workflow that runs whenever `v*` tags are pushed. It'll create a release build and upload the assets to a drafted Github release. This will still require that a human intervenes to make the release public and add any pertinent release notes.
=> Release action

ci/integration/images_test.go, coder-sdk/image.go, coder-sdk/tags.go, docs/coder.md, docs/coder_images.md, docs/coder_images_ls.md, internal/cmd/cmd.go, internal/cmd/images.go
Allows users to list imported images.
By default, a `coder images ls` will list every imported image for every organization a user belongs to.
The default output is a human-readable table that describes the default resource amounts for each image :
```
Repository                                               DefaultTag    DefaultCPUCores    DefaultMemoryGB    DefaultDiskGB    
ubuntu                                                   latest        1                  1                  10               
nixos/nix                                                latest        2                  2                  10               
cdecelles/sts                                            latest        1                  1                  10               
java …
```
=> Implement coder images ls

coder-sdk/devurl.go, internal/cmd/urls.go
We can add a flag for specifying the scheme down the line.
=> Use default scheme of http for dev urls

coder-sdk/activity.go, coder-sdk/config.go, coder-sdk/devurl.go, coder-sdk/env.go, coder-sdk/image.go, coder-sdk/org.go, coder-sdk/registries.go, coder-sdk/secrets.go, coder-sdk/tags.go, coder-sdk/tokens.go, coder-sdk/users.go, coder-sdk/version.go
This PR migrates all routes to the new `/private` route prefix. This is part of a larger effort to standardize and release proper API documentation. Over the next several releases, we'll be migrating route groups from `/private` to `/v1` and releasing OpenAPI docs for reference.
=> Migrate all API routes to /api/private

coder-sdk/users.go, internal/cmd/configssh.go
In optimizing the dashboard environment experiences, tracking whether a user has run config-ssh locally enables personalized education about the feature.
1. I downloaded and ran `coder config-ssh` using the binary attached to the CI run
2. I verified that my ux state was updated
=> cli: Update UXState from config-ssh

internal/cmd/configssh.go
https://github.com/cdr/c/pull/6095#issuecomment-738496271
`cliSSHConfigured` is changing data structure from `bool` -> `map[string]bool` in order to capture which environments are configured for SSH.
=> Use environment dictionary in config-ssh ux state call

.github/workflows/build.yaml, .github/workflows/release.yaml, Makefile, ci/integration/Dockerfile, ci/integration/setup_test.go, ci/steps/build.sh, pkg/tcli/tcli.go
This PR modifies the build process to use an ubuntu runner for windows/linux binary compilation. This fixes some Windows Defender issues caused by macOS go cross compilation.
=> Build linux/windows on ubuntu runner

docs/coder_envs.md, docs/coder_envs_create.md, docs/coder_envs_edit.md, docs/coder_envs_ls.md, docs/coder_envs_rebuild.md, docs/coder_envs_rm.md, docs/coder_envs_stop.md, docs/coder_envs_watch-build.md, internal/cmd/envs.go, internal/cmd/rebuild.go
This PR removes the persistent --user flag from the `coder envs create` command.
=> Remove --user flag from "envs create"

internal/cmd/ceapi.go, internal/cmd/shell.go
Closes #213
```
$ coder sh
error: missing [environment_name] argument
| specify one of ["test7" "test6" "test3" "test1"]
| 
| tip: run "coder envs ls" to view your environments
exit status 1
$ coder sh fakename
fatal: failed to find environment
| environment "fakename" not found in ["test7" "test6" "test3" "test1"]
| 
| tip: run "coder envs ls" to view your environments
exit status 1
```
I'm considering adding special handling for `--help` and `-h`.
=> chore: cleanup error output for "coder sh"

coder-sdk/env.go, coder-sdk/request.go, coder-sdk/resourcepools.go, coder-sdk/ws.go, internal/cmd/configssh.go, internal/cmd/shell.go, internal/coderutil/doc.go, internal/coderutil/env.go, internal/sync/singlefile.go, internal/sync/sync.go
=> chore: use access url from env resource pool

ci/integration/envs_test.go, coder-sdk/image.go, coder-sdk/registries.go
- This is part of an ongoing effort to standardize
our API for public consumption. This fixes some routes
that broke backwards compatibility (specifically
image and registry routes).
=> chore: update API routes for images/registries

internal/cmd/shell.go
When creating a shell, we should use "exec -a" to set argv[0]
to the basename of the command being run, prefixing a hyphen.
This is how su --login creates login shells: it runs /bin/bash
as "-bash", causing bash to execute .bash_profile, etc.
We change the use of awk to cut, since cut is part of coreutils
and thus more likely to be installed than gawk. We also pass the
uid (from "id -u") instead of username to getent.
=> Create login shell with coder sh

coder-sdk/env.go, docs/coder_sh.md, internal/cmd/shell.go
When a user does `coder sh <env>`, the cli first checks if that environment is `OFF` or if it requires a rebuild before using. It will then prompt the user if they want to rebuild the workspace.
**Off**
```
coder env stop <workspace>
coder sh <workspace>
```
**Rebuild Message**
If the environment has a required rebuild message, the output looks like this:
Currently `--force` does not work for this feature, and there is no `--no-rebuild` flag. The current command has flag parsing disabled. Are these kinds of flags required? I imagine a user prompt would make scripting `coder sh` rather annoying.
=> feat: Prompt user to rebuild workspace on coder sh

go.mod, internal/cmd/cmd.go, internal/cmd/envs.go, internal/cmd/login.go, internal/cmd/rebuild.go, internal/cmd/sync.go, internal/cmd/tags.go, internal/cmd/tokens.go, internal/cmd/urls.go, internal/x/xcobra/cobra.go
Closes #200 
```
╰─>$ coder login
error: accepts 1 arg(s), received 0
| usage: coder login [Coder Enterprise URL eg. https://my.coder.domain/] [flags]
| 
| tip: use "--help" for more info
exit status 1
```
=> feat: improved arg usage errors

internal/cmd/shell.go
This addresses a regression introduced by #224. POSIX `sh` does not define arguments to the `exec` built-in, resulting in an error when using `exec -a` to set the process name (`argv[0]`).
This change executes `/bin/bash` instead of `sh`, and also changes to use `exec -l`, which automatically handles the hyphen prefix required to trigger login shell behavior.
This also explicitly runs `/bin/sh`, aligning the behavior of `coder sh` and the frontend Terminal application.
Tested this using Arch Linux (enterprise-dev image) as well as the base Debian image from DockerHub.
```console
[coder@jawnsy-m coder-cli]$ go install ./cmd/coder
[coder@jawnsy-m coder-cli]$ which coder
/home/coder/go/bin/coder
[coder@jawnsy-m coder-cli]$ coder sh jawnsy-m
| Coder CLI …
```
=> fix: Force bash for non-standard flags to exec

internal/cmd/shell.go, internal/cmd/shell_test.go
The commands passed to "coder sh" are passed as a single argument to "sh -c", so we need to shell-escape the command we pass. This change escapes spaces, backslash, and quotes.
I'm not 100% sure if this is a good idea, since it is a breaking change in case people have already been escaping their commands.
Note: this will need to be rebased once #226 is merged
Tested as follows:
```console
[coder@jawnsy-m coder-cli]$ go install ./cmd/coder
[coder@jawnsy-m coder-cli]$ which coder
/home/coder/go/bin/coder
[coder@jawnsy-m coder-cli]$ coder sh jawnsy-m go run ~/test.go 1 2 "3 4" '"abc def" \\abc' 5 6 "7 8 9"
| Coder CLI version: unknown
| Coder API version: 1.14.0+340-gd64a44cb3-20210123
| 
| tip: download the appropriate version here: …
```
=> fix: Escape shell arguments

ci/integration/integration_test.go, docs/coder.md, docs/coder_tokens.md, docs/coder_tokens_create.md, docs/coder_tokens_ls.md, docs/coder_tokens_regen.md, docs/coder_tokens_rm.md, internal/cmd/tokens.go
* Mark tokens subcommand as visible
* Re-generate Markdown documentation for the commands
* Add JSON output for "tokens ls" command, as with "envs ls"
* Add integration test cases
Tested the commands:
```console
[coder@jawnsy-m docs]$ coder tokens ls -o json
| Coder CLI version: unknown
| Coder API version: 1.14.0+351-gb3b505259-20210124
| 
| tip: download the appropriate version here: https://github.com/cdr/coder-cli/releases
[{"id":"RQAv4Tvhiw","name":"abc","application":true,"user_id":"6006fa81-d49b8c0d52e920fe40f5ca90","last_used":"0001-01-01T00:00:00Z"},{"id":"rAvv33PmmY","name":"","application":false,"user_id":"6006fa81-d49b8c0d52e920fe40f5ca90","last_used":"2021-01-22T21:19:58.65074Z"},{"id":"XTCWEeOvoo","name":"","application":false,"user_id":"600 …
```
=> feat: Reveal tokens subcommand

coder-sdk/env.go, coder-sdk/request.go, coder-sdk/ws.go, internal/cmd/envs.go
- Add an endpoint to parse a WAC template.
- Add support for specifying a local file.
- Decoupled creating an environment from parsing a template
(in the API).
=> feat: split parsing config from creating env

internal/cmd/configssh.go
This setting will prevent ssh from using identities found in ssh-agent. We're
already specifying the identity file, so there's no need to rely on ssh-agent
for this.
This will prevent 'too many authentication failures' errors when connecting to
an environment while having a lot of identities loaded in the agent.
=> Set IdentitiesOnly option when configuring ssh

internal/cmd/rebuild.go
The server-sent ISO8601 timestamps are not necessarily in the user's
preferred timezone. This change uses time.Local() to get the time in
the user's local time according to their system settings.
Success case, interactive terminal:
```console
[coder@jawnsy-m coder-cli]$ coder envs watch-build jawnsy-m 
| Coder CLI version: unknown
| Coder API version: 1.14.0+709-g75124e3d4-20210211
| 
| tip: download the appropriate version here: https://github.com/cdr/coder-cli/releases
✅ -- 2021-02-11T16:21:12-08:00 Your environment was queued for rebuilding
✅ -- 2021-02-11T16:21:16-08:00 Deleting old environment
✅ -- 2021-02-11T16:21:16-08:00 Deleting old network isolation policy
✅ -- 2021-02-11T16:21:16-08:00 Deleting old service
✅ -- 2021-02-11T16:21:16-08:00 …
```
=> feat: show build log timestamps in local time

.github/workflows/test.yaml, Makefile
* Update actions to latest versions
* Update golangci-lint to latest version, 1.36
* Pin Ubuntu to the latest, version 20.04
* Add coverage profiling test and send results to Coveralls
=> chore: add code coverage reporting

coder-sdk/env.go, docs/coder_envs_create.md, internal/cmd/envs.go, internal/cmd/rebuild.go
I tried my best to get some cool info/ed information around AutoStart into the CLI :zap:
I added this to:
- envs create
- envs rebuild
```
$ go run ./cmd/coder/main.go envs create created-from-cli --image ubuntu --enable-autostart --org Coder
info: ⚡NEW: Automate daily environment startup
| Visit https://master.cdr.dev/preferences?tab=autostart to configure your preferred time
| Coder CLI version: unknown
| Coder API version: 1.14.0+743-g7c24d16bb-20210216
| 
| tip: download the appropriate version here: https://github.com/cdr/coder-cli/releases
success: creating environment...
| 
| tip: run "coder envs watch-build created-from-cli" to trail the build logs
```
Should we accept this effort, we should spawn a ticket to remove the education notice from the …
=> feat(cli): AutoStart education notice [ch7441]

ci/integration/envs_test.go, coder-sdk/activity.go, coder-sdk/client.go, coder-sdk/client_test.go, coder-sdk/config.go, coder-sdk/devurl.go, coder-sdk/env.go, coder-sdk/image.go, coder-sdk/interface.go, coder-sdk/org.go, coder-sdk/registries.go, coder-sdk/request.go, coder-sdk/tags.go, coder-sdk/tokens.go, coder-sdk/users.go, coder-sdk/version.go, coder-sdk/workspace_providers.go, coder-sdk/ws.go, internal/activity/pusher.go, internal/cmd/auth.go, internal/cmd/ceapi.go, internal/cmd/configssh.go, internal/cmd/envs.go, internal/cmd/login.go, internal/cmd/rebuild.go, internal/cmd/shell.go, internal/cmd/urls.go, internal/coderutil/env.go, internal/sync/singlefile.go, internal/sync/sync.go
* Create Client interface, so that it can be mocked/stubbed
* Validate client options at creation time
* Reuse internal HTTP Client, so that we have connection pooling
* Send the Session-Token in a header rather than cookie
=> feat: reuse http.Client and validate client options at creation time

coder-sdk/client.go, coder-sdk/client_test.go, coder-sdk/login.go
This enables authenticating to Coder using the coder-sdk using an
email/password combination (basic authentication). As it is intended
for test purposes only, it is not exposed via coder-cli.
=> feat: add password authentication to coder-sdk

coder-sdk/client.go, coder-sdk/client_test.go, coder-sdk/interface.go, coder-sdk/users_test.go
This adds accessors to retrieve the Client's active Session Token
and Base URL.
=> chore: expose API Token and BaseURL

coder-sdk/env.go, internal/cmd/envs.go, internal/coderutil/env.go
We can expose these values via a flag later, but for now using the default pool is OK.
=> chore: provide resource pool id and namespace in env create

ci/integration/envs_test.go, coder-sdk/activity_test.go, coder-sdk/client_test.go, coder-sdk/users_test.go, go.mod, internal/loginsrv/input_test.go, internal/loginsrv/server_test.go
This switches tests from stretchr/testify to our preferred slogtest
assertion library.
=> chore: remove dependency on stretchr/testify

.github/dependabot.yml
* Ignore minor versions for actions/cache and actions/checkout,
since GitHub always replaces the v2 tag with the latest minor
release
* Remove assignee setting, since it doesn't seem to work
=> chore: ignore minor versions for official actions

coder-sdk/error.go, internal/cmd/envs.go, internal/cmd/errors.go
Related to: https://github.com/cdr/m/pull/7373
In addition to the errors reported in the `/m` pr, this also now expands verbose errors. These verbose errors are not yet reviewed for human readability:
```
error: unexpected status code 500: An internal server error occurred.
| read file: get file contents: GET https://api.github.com/repos/Emyrk/te/contents/.coder/coder.yaml?ref=master: 404 Not Found []
```
```
error: unexpected status code 500: An internal server error occurred.
| parse repo url: unexpected url "", expecting at least an owner and a repo
```
```
error: unexpected status code 500: An internal server error occurred.
| exec select: pq: relation "images" does not exist
```
=> Handle wac template parse errors

coder-sdk/workspace_providers.go, internal/coderutil/env.go
for https://github.com/cdr/m/pull/7397
=> Rename local pools to built-in

internal/cmd/cmd.go, internal/cmd/envs.go, internal/cmd/images.go, internal/cmd/login.go, internal/cmd/rebuild.go, internal/cmd/resourcemanager.go, internal/cmd/shell.go, internal/cmd/sync.go, internal/cmd/tags.go, internal/cmd/tokens.go, internal/cmd/urls.go, internal/cmd/users.go, internal/sync/sync.go, internal/sync/title.go, pkg/clog/clog.go, pkg/clog/clog_test.go
By moving the out/err/in channels to the cobra config,
it will be easier to add fast and isolated unit tests.
=> chore: limit direct uses of os.Stdout/os.Stderr/os.Stdin

coder-sdk/workspace_providers.go, internal/cmd/providers.go
must be merged before https://github.com/cdr/m/pull/7417
=> Validate hostname, name, and cluster address on wsp create

internal/cmd/envs.go, internal/cmd/envs_test.go, internal/cmd/images.go, internal/cmd/providers.go, internal/cmd/tags.go, internal/cmd/tokens.go, internal/cmd/urls.go, internal/cmd/users.go, internal/config/dir.go, pkg/tablewriter/tablewriter.go, pkg/tablewriter/tablewriter_test.go
More to come of course, but want to merge these many-file diffs in small PRs to reduce blocking and conflicts.
The next major inhibitor to test flexibility is the fact that our `config` values are mostly package-level. Will need to refactor.
=> chore: simple no auth unit test

coder-sdk/env.go, coder-sdk/image.go, coder-sdk/interface.go, coder-sdk/workspace_providers.go, internal/cmd/envs.go, internal/coderutil/env.go
```
$ coder envs ls
Name          Image                                         vCPU    MemoryGB    DiskGB    Status    Provider    CVM      
test          codercom/enterprise-base:ubuntu               1       1           10        ON        built-in    true     
dev           coder-dogfood/master/enterprise-dev:latest    16      32          196       ON        built-in    true     
test12        codercom/enterprise-base:ubuntu               1       1           10        ON        built-in    true     
testing123    ubuntu:latest                                 1       1           10        OFF       built-in    false
```
=> feat: add provider name and repo name to envs ls

internal/cmd/providers.go
Example:
```
➜  coder-cli git:(master) ✗ go run cmd/coder/main.go providers create cli-test-2 --hostname=http://cli-test.master.cdr.dev --cluster-address=https://104.154.56.145
success: 
Created workspace provider "cli-test-2"
ID                                   Name          Status     Envproxy Token                       
604aca11-5f959b6c46fe9ef188a621b3    cli-test-2    pending    604aca11-5fc1688feae792c669d130b3    
Now that the workspace provider is provisioned, it must be deployed into the cluster. To learn more,
visit https://coder.com/docs/guides/deploying-workspace-provider
When connected to the cluster you wish to deploy onto, use the following helm command:
helm upgrade coder-workspace-provider coder/workspace-provider \
--version=1.17.0-rc.1+27-g0c229ed3a-20210311 \ …
```
=> Add documentation after provider create

internal/cmd/resourcemanager.go
Fixes the `len` of the `providerEnvs` map in the grouping func when filtering by providers.
=> fix: wrong len arg in provider aggregator

internal/cmd/resourcemanager.go
So the difference here is rather subtle and bit counterintuitive. We want to "label" by the property which is not being grouped by. So in this case we only want to "label" the provider when we are grouping my user/org. 
It's completely redundant to label each environment with the provider when they are already grouped together and have the provider in the group header.
=> fix: properly label by non grouped property

internal/cmd/resourcemanager.go, internal/coderutil/env.go
The verbose output does seem to have gotten quite wide... probably worth considering adding a `--label` flag where the caller can opt-in to labels. I removed the `alloc=` resource prefixes since those don't exactly make sense until we have `util` metrics. I'm not too worried though given that this is `hidden: True`.
```
coder resources top --group org --verbose
Coder    (53 members)    [cpu: 128.0vCPU]    [mem: 144.0GB]
dev                [cpu: 16.0vCPU]    [mem: 16.0GB]    [user: garrett@coder.com]     [img: coder-dogfood/master/enterprise-dev:latest]    [provider: built-in]
dev                [cpu: 16.0vCPU]    [mem: 16.0GB]    [user: kyle@coder.com]        [img: coder-dogfood/master/enterprise-dev:latest]    [provider: built-in]
jawnsy-m           [cpu: 16.0vCPU]    [mem: 16.0GB] …
```
=> feat: add image:tag label to resources top

internal/cmd/envs_test.go, internal/cmd/resourcemanager.go, internal/cmd/resourcemanager_test.go, internal/cmd/resourcemanager_test.golden
Similar to what we do in `tablewriter`, we have tests that assert the output matches the `.golden` file. 
When making intentional changes to the output, just pass the `-write` flag and it'll overwrite the golden file. Then of course be sure to verify that the new output looks appropriate.
=> chore: add golden file tests for `resources top`

Makefile, ci/integration/integration_test.go, coder-sdk/interface.go, coder-sdk/workspace_providers.go, internal/cmd/providers.go
Implements two new subcommands.
`coder providers cordon --reason "cloud cost" provider-name`
Allows users to cordon a provider; preventing it from supporting new workspaces.
**Note** : the `--reason` flag is required to explain why this action was performed.
`coder providers uncordon provider-name`
Also supports uncordoning a provider; allowing the provider to continue provisioning resources for new workspaces.
=> feat: implement cordon/uncordon workspace provider

internal/cmd/envs.go
Add `--name` flag to `create-from-config`
```bash
coder envs create-from-config -r https://github.com/Emyrk/test --ref=master --name="wac-env" 
```
For https://github.com/cdr/m/pull/7619
Also drop `repo url` validation, server now does it better: https://github.com/cdr/m/pull/7615 
```bash
error: Precondition Error : Status Code=412
| The Git Repository URL should be using https://, the provided repository url "git@github.com:Emyrk/test" does not.
| 
| tip: Try using "https://github.com/Emyrk/test.git" instead
```
=> Removing `Name` from Wac templates

internal/cmd/login.go
See CH10090 https://app.clubhouse.io/coder/story/10090/coder-login-fails-windows-command-prompt-1-17-2
Switches to bufio.Scanner for reading the token. Thanks @jawnsy for the guidance
before: 
```sh
C:\Users\victo>coder login https://dev.coding.pics
Your browser has been opened to visit:
https://dev.coding.pics/internal-auth?show_token=true
Paste token here: REDACTED
fatal: login error: ping API with credentials: call api: Execute request: "Get \"https://dev.coding.pics/api/v0/users/me\": net/http: invalid header field value \"REDACTED\\r\" for key Session-Token"
C:\Users\victo> coder version
coder version v1.17.2 go1.15.10 windows/386
```
Edit: tested on Windows 10 and OSX to confirm it worked
=> Fix `coder login` on Windows

docs/coder_config-ssh.md, internal/cmd/agent.go, internal/cmd/cmd.go, internal/cmd/configssh.go, internal/cmd/tunnel.go
The `tunnel` command takes in an environment name, a remote port, and a local port and makes a TCP tunnel to connect via webrtc. 
```
➜  coder-cli git:(cmd-tunnel) ✗ go run cmd/coder/main.go tunnel test-1 8000 7000
2021-04-08 14:24:53.660 [INFO]  <tunnel.go:108> connecting to broker    {"url": "http://demo.f0ssel.io/api/private/envagent/60663b9f-d9cf66c1a000789e2d32c431/connect?session_token=IqragYByIf-p3ovf4fX3aH4dr0i99K1Bz"}
2021-04-08 14:24:53.906 [INFO]  <tunnel.go:126> connection state changed        {"state": "connected"}
2021-04-08 14:24:53.910 [INFO]  <tunnel.go:208> your latency directly to the agent      {"ms": 0}
```
I've also added a `--p2p` flag to the `coder config-ssh` command, so it will edit the ssh config to use the coder tunnel instead of tradition ssh. This will allow …
=> Add coder tunnel command

agent/doc.go, agent/server.go, agent/stream.go, go.mod, go.sum, internal/cmd/agent.go
This organizes the code to into a new `agent` pkg, in hopes we can share some code with the coder repo as well when the time comes.
I wrap the main server in a retry loop to make sure the agent is always running (if it get's passed the input parsing in the command)
=> Add retries to coder agent start cmd

internal/cmd/envs.go, internal/cmd/rebuild.go
For `1.18` April release, it seems safe to remove the autostart education notice that's been in place since February (`1.16`)
=> feat: Remove autostart ed notice

coder-sdk/interface.go, coder-sdk/workspace_providers.go, internal/cmd/providers.go
This allows users to change the name of a workspace provider with `coder providers rename old-name new-name`
=> Add coder providers rename command

.golangci.yml, agent/server.go, internal/cmd/tunnel.go
The error messages for failed p2p connections are opaque. This PR  unmarshals the HTTP response from a failed websocket dial if it exists. 
```bash
coder@dev coder (p2p) ./coder tunnel foo 8080 8080
2021-04-22 02:40:48.886 [INFO]	<tunnel.go:112>	connecting to broker	{"url": "https://sreya.dev.c8s.io/api/private/envagent/607f7924-00381cbee0bf0e359aab077a/connect?session_token=6Sr4KLknFL-zMKMh2qh7G0t1ldRSI0nSI"}
2021-04-22 02:40:48.910 [FATAL]	<tunnel.go:89>	The P2P feature has not been enabled for this deployment. To use this feature set 'cemanager.p2p.enable: true' in your helm configuration
```
=> chore: unmarshal HTTP errors for p2p commands

internal/cmd/tunnel.go, wsnet/dial_test.go, wsnet/rtc.go, wsnet/rtc_test.go
Fixes `IgnoreSkipVerify` always being true.
=> fix: Add TLS option to DialICE

wsnet/auth.go, wsnet/dial_test.go, wsnet/listen.go, wsnet/rtc.go
=> fix: Loop Dial for reconnects

coder-sdk/devurl.go, docs/coder_urls.md, docs/coder_urls_create.md, internal/cmd/urls.go
```console
$ go run ./cmd/coder/main.go  urls create --help
Create a new dev URL for a workspace
Usage:
coder urls create [workspace_name] [port] [flags]
Aliases:
create, edit
Examples:
coder urls create my-workspace 8080 --name my-dev-url
Flags:
--access string   Set DevURL access to [private | org | authed | public] (default "private")
-h, --help            help for create
--name string     DevURL name
--scheme string   Server scheme (http|https) (default "http")
Global Flags:
-v, --verbose   show verbose output
```
```console
$ go run ./cmd/coder/main.go urls create grey-m-built-in 3001
success: created devurl for port 3001
```
```console
URL                                                  Port    Access     Name     Scheme    
https://3001-grey-m-built-in-grey.<REST_IS_OBFUSCATED>/ …
```
=> fix: Optional --name for urls create [ch8011]

wsnet/listen.go, wsnet/listen_test.go
We were checking if the dialer would retry once, which it always would.
This ensures the dialer retries infinitely, as long as:
- The context isn't expired.
- The first connection was successful.
=> fix: Retry RTC connection attempts multiple times

wsnet/listen.go
Pretty unfortunate bug here... noticed while testing.
After the initial dial the loop was never exited, causing infinite redials.
=> fix: Stop looping retries after dial failure

wsnet/conn.go
Caused strings like `localhost:5349:8080` when a hostname contained a port.
=> fix: Drop port when creating TURN endpoint

wsnet/dial.go, wsnet/listen.go, wsnet/proto.go, wsnet/proto_test.go, wsnet/rtc.go
Adds `Policies` field to `ProtoMessage` which denotes which network + host + port combinations a client connection may use. Makes `ProtoMessage` public.
=> wsnet dial policy

.github/workflows/test.yaml, go.mod, wsnet/conn.go, wsnet/dial.go, wsnet/dial_test.go, wsnet/listen.go, wsnet/rtc.go, wsnet/wsnet_test.go
Passes random sizes of byte slices through the connection to ensure buffering works as expected.
```bash
rem ~/P/c/coder-cli (rtcbench) go test -bench 'BenchmarkThroughput' cdr.dev/coder-cli/wsnet
goos: linux
goarch: amd64
pkg: cdr.dev/coder-cli/wsnet
cpu: Intel(R) Xeon(R) CPU
BenchmarkThroughput/Rand4-32               59210             19854 ns/op           0.20 MB/s        3002 B/op         88 allocs/op
BenchmarkThroughput/Rand16-32              58438             20366 ns/op           0.79 MB/s        3161 B/op         88 allocs/op
BenchmarkThroughput/Rand128-32             47649             23671 ns/op           5.41 MB/s        4817 B/op         89 allocs/op
BenchmarkThroughput/Rand256-32             48429             24614 ns/op          10.40 MB/s        6834 B/op         91 …
```
=> feat: Add Benchmarks to test WebRTC connections

wsnet/dial.go, wsnet/dial_test.go, wsnet/rtc.go
Previously, Ping() would hang forever due to the DataChannel
never closing when the RTC connection ended.
=> fix: Close Ping DataChannel when connection ends

wsnet/dial.go, wsnet/dial_test.go, wsnet/rtc.go, wsnet/wsnet_test.go
Previously the error occurred but never propogated due to blocking fromm
the read loop in negotiate. Now, connection timeouts can properly occur.
=> fix: Close conn if context deadline is exceeded

.github/workflows/release.yaml, Makefile, ci/scripts/build.sh, go.mod, go.sum, internal/cmd/configssh.go
In Powershell and VS Code, the OpenSSH for Windows `ProxyCommand` is expected to be a binary name like `coder` or a Windows-like path such as `C:\path\to\coder.exe`.
In Msys2 and Git Bash, the Linux-y OpenSSH expects the `ProxyCommand` to be a binary name or a Unix-like path such as `/c/path/to/coder`.
To support both environments simultaneously, the `ProxyCommand` must be set to `coder` (or whatever binary name coder-cli has), and we must warn the user if the binary is not in `$PATH`.
[CH-15394]
=> Warn if coder-cli is not in PATH on Windows

docs/coder_config-ssh.md, internal/cmd/configssh.go
=> feat: Enable arbitrary SSH options passed via config-ssh

internal/cmd/configssh.go, internal/cmd/ssh.go
=> Use webrtc for coder sh

internal/cmd/ceapi.go, internal/cmd/workspaces.go, internal/cmd/workspaces_test.go
From an admin POV, this will be helpful for various reasons.
=> feat: Option to list all workspaces

.github/workflows/build.yaml, .github/workflows/integration.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml
* Update actions/checkout from v1 to v2
* Configure build to run on pushes/pull requests on main
* Add restrictive workflow permissions
* Update minimum setup-go from 1.16.3 to 1.16.7
* Enable workflow dispatch for all builds
=> chore: update build settings for coder-cli

coder-sdk/workspace.go, docs/coder_workspaces_create-from-config.md, docs/coder_workspaces_edit-from-config.md, internal/cmd/workspaces.go
Fix a few stray uses of the legacy "environments" terminology (envs)
and replace it with "workspaces."
=> fix: rename envs to workspaces

internal/cmd/agent.go
Running the agent, the log data is written to a file as well (and truncated/re-created on subsequent starts):
```shell-session
$ go run ./cmd/coder/main.go agent start
2021-09-02 01:36:32.847 [INFO]  <agent.go:90>   starting wsnet listener {"coder_access_url": "https://master.cdr.dev"}
2021-09-02 01:36:32.848 [INFO]  <listen.go:114> connecting to broker    {"broker_url": "wss://master.cdr.dev/api/private/envagent/listen?service_token=xxx"}
2021-09-02 01:36:32.928 [INFO]  <listen.go:136> broker connection established
^C2021-09-02 01:36:53.420 [INFO]        <agent.go:96>   closing wsnet listener
2021-09-02 01:36:53.421 [INFO]  <listen.go:451> listener closed
$ cat /tmp/coder-agent.log 
2021-09-02 15:22:25.006 [INFO]  <agent.go:92>   starting wsnet listener {"coder_access_url": …
```
=> feat: write agent output to a temporary file

internal/cmd/agent.go
New help output:
```shell-session
$ go run ./cmd/coder/main.go agent start --help
starts the coder agent
Usage:
coder agent start --coder-url=<coder_url> --token=<token> --log-file=<path> [flags]
Examples:
coder agent start
coder agent start --coder-url https://my-coder.com --token xxxx-xxxx
coder agent start --log-file=/tmp/coder-agent.log
Flags:
--coder-url string   coder access url
-h, --help               help for start
--log-file string    write a copy of logs to file
--token string       coder agent token
Global Flags:
-v, --verbose   show verbose output
```
Log to file:
```shell-session
$ go run ./cmd/coder/main.go agent start --log-file=/tmp/file.log
2021-09-02 19:23:22.255 [INFO]  <agent.go:100>  starting wsnet listener {"coder_access_url": "https://master.cdr.dev"}
2021-09-02 …
```
=> feat: make log file path optional and configurable

coder-sdk/workspace.go, docs/coder_workspaces_create.md, internal/cmd/workspaces.go
Adds a `--user` on creating a workspace for another user. Must be an admin/manager to do this.
Create a workspace for a user
```
coder workspaces create test --cpu 1 --disk 1 --memory 1 --image ubuntu --user steven@gmail.com
```
Watch it build
```
coder workspaces watch-build base-img --user steven@gmail.com
```
View the workspace
```
coder workspaces ls --user steven@gmail.com 
```
Delete the workspace
```
coder workspaces rm --user steven@gmail.com test
```
=> feat: Allow making a workspace for another user as an admin

internal/cmd/configssh.go, internal/cmd/ssh.go, internal/cmd/users_test.go
=> chore: Use webrtc for coder sh (#408)

internal/cmd/update.go, internal/cmd/update_test.go
* Use `semver.NewVersion` instead of `semver.StrictNewVersion` as otherwise users must type the explicit trailing zeros e.g. `coder update --version 1.21.0` instead of `coder update --version 1.21`.
=> fixup! feat: Add update command to coder-cli (#417)

README.md
See [internal discussion](https://codercom.slack.com/archives/C015YDF37AT/p1672859001777719).
=> docs(readme): reduce a11y so coder v2 users don't stumble upon this
